import "./globals.css";

export const metadata = {
  title: "Green Habits",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="icon"
          href="../assets/logo.png" 
        />
      </head>
      <body>
        {children}
      </body>
    </html>
  );
}
