import "./globals.css";

export const metadata = {
  title: "Climate Tracker",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: '/logo.png' },
      new URL('/logo.png', 'https://example.com'),
      { url: '/logo.png', media: '(prefers-color-scheme: dark)' },
    ],
    shortcut: ['/logo.png'],
    apple: [
      { url: '/apple-icon.png' },
      { url: '/apple-icon-x3.png', sizes: '180x180', type: 'image/png' },
    ],
    other: [
      {
        rel: 'apple-touch-icon-precomposed',
        url: '/apple-touch-icon-precomposed.png',
      },
    ],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
